### PR TITLE
Adding Guide entry for Openstack provider.

### PR DESCRIPTION
**Pull request by elsonrodriguez**
This fixes the missing header/toc issue.

http://elsonrodriguez.github.io/docs/getting-started-guides/openstack-heat/

### CODE REVIEW

**Comment by elsonrodriguez** [comment]
@zreigz This should be it.

**Comment by zreigz** [comment]
LGTM

**Comment by cheld** [comment]
Hello @elsonrodriguez,

to be honest our focus shifted a bit from the salt-based provisioning to the future docker-based provisioning. That's why we are a bit negligent about our contributed openstack provider. If there is anything we should do please let us know.

BTW: we have created an experimental repo that creates a cluster based on heat and docker and cni. (It also contains some enhancements/fixes have been too late to be merged upstream - because of 1.3 feature freeze). If you like you can have a look:

https://github.com/FujitsuEnablingSoftwareTechnologyGmbH/k8s-docker-provisioner

Best regards,

Christoph

**Comment by elsonrodriguez** [comment]
@cheld 

No worries, but I'm shifting my focus away from Openstack entirely, so I might not have the bandwidth for when 1.3 hits either.

I'll take a look at the provisioner, but you definitely want to reach out to the people in #sig-openstack on the Kubernetes slack chat and see if you can build some kind of support/consensus there.

(P.S. i've opened a PR to fix this in the main k8s doc repo)

**Pull request merged**
