### PR TITLE
Rewrite of Openstack provider documentation.

### PR DESCRIPTION
**Pull request by elsonrodriguez**
Ended up rewriting much of the documentation while adding new functionality.

Please give it a read.

### CODE REVIEW

**Comment by elsonrodriguez** [comment]
@zreigz @ohtake I wasn't able to test some things due to issues with our OpenStack install. If you could run through the guide on your local install and provide feedback it will be of great help.

**Comment by zreigz** [comment]
Yes sure I will test it

**Comment by elsonrodriguez** [comment]
@zreigz @cheld @ohtake I've ran through the documentation a few more times and smoothed things out.

If nothing seems amiss, this should be merged (especially to match the PR)

**Comment by elsonrodriguez** [comment]
@ohtake Can you merge this one too?

**Comment by cheld** [comment]
@elsonrodriguez thanks a lot

**Pull request merged**
